Creating the countdown in the header
ReactFinland/site pull request #53
Opened 2018-02-27 11:02 UTC by Scoombe

I have had a go at addressing  issue #26. I need some pointers on the style of the change, also this is my first time looking at react so any help there would be nice.

2018-02-27 11:02 UTC, bebraw commented
Deploy preview for *react-finland* processing.

Built with commit 94b0a22bb81142eb25e2d8bce8f664e3bccce772

https://app.netlify.com/sites/react-finland/deploys/5a953acba6188f6e6f9fb232

2018-02-27 13:08 UTC, bebraw commented
That's a great start!

Check `pages/for-attendees.js` on how to wrap the component to an `Interactive` container. After that the counter works also in the production version. This is a small limitation of the static site generator and I might fix this later. But for now we have to wrap it.

@manpenaloza @okonet Can you provide some guidance on the visual outlook? [Preview here](https://5a953acba6188f6e6f9fb232--react-finland.netlify.com/).

2018-02-27 13:21 UTC, bebraw commented
Inspiration: https://dribbble.com/tags/countdown_timer . Something along https://dribbble.com/shots/3825256-Daily-UI-challenge-014-Countdown-timer would look cool perhaps. I would do it horizontal like that but with tuned style.

2018-02-27 14:10 UTC, manpenaloza commented
nice one!

Horizontal look could be a good choice, wireframed sth for further implementation. what do you think?
![react-finl-countdown](https://user-images.githubusercontent.com/4241744/36733229-3bd3e238-1bd0-11e8-9eb3-96489e13ecb2.jpg)

2018-02-27 14:26 UTC, bebraw commented
@manpenaloza That looks great to me! We can use the font we already have. The layout is just 👍 .

2018-02-27 14:35 UTC, Scoombe commented
@manpenaloza Looks good! @bebraw  What steps should be taken now?

2018-02-27 14:36 UTC, bebraw commented
@Scoombe Would you be comfortable porting to the proposed layout? You can also try `Interactive`. Let me know if you get stuck and I can manage the rest. 👍

2018-02-27 14:46 UTC, Scoombe commented
@bebraw I would be, what's the best way to do this? Inline css in the react component or adding to the existing css files? I might not get time to do this until Friday if that's ok.

2018-02-27 14:52 UTC, bebraw commented
@Scoombe No rush. Maybe separate CSS like for now. I might integrate a css-in-js solution (Emotion) later.

2018-02-27 16:42 UTC, okonet requested changes

2018-02-27 16:42 UTC, okonet commented on components/Countdown.js
> +var React = require("react");
Any reason not to use `Import` here?

2018-02-27 16:42 UTC, okonet commented on components/Countdown.js
> +    this.TimeDiff = this.timeDiff();
Can these 2 be renamed into something more destinguishable and readable. Also, please don’t use CamelCase for instance variables.

2018-02-27 16:42 UTC, okonet commented on components/Countdown.js
> +    this.TimeDiff = this.timeDiff();
Why does it needs to be stored in the instance variable BTW? It looks like a state since you’re rendering those values.

2018-02-27 16:42 UTC, okonet commented on components/Header.js
>  const Header = ({ pathname, title }) => {
A new line is missing afaik

2018-02-27 16:42 UTC, okonet commented on components/Countdown.js
> +          {this.TimeDiff.days} Days&#160;
Storing deriving values is an anti-pattern. You could just call the `timediff` in the render method instead.

2018-02-27 16:44 UTC, okonet commented
Can we move the counter below the tagline?

2018-03-02 11:35 UTC, Scoombe commented
@bebraw @manpenaloza  I have made some changes, but I need some help with the css. Could you help with this. Thanks.

2018-03-02 13:25 UTC, okonet requested changes

2018-03-02 13:25 UTC, okonet commented on components/Countdown.js
> +    this.Difference = this.getDifferenceInDates();
What's the point for storing those values as an instance variable? Let's simplify a bit by moving getting all derived values in the `render` method:

```js
render() {
  const { days, hours, minutes, seconds } = timediff(this.state.currentDate, this.props.initialDate, "D:H:m:S");
  ...
}
```

and remove all instance variables. The only thing you'll need to store in the state is the `currentDate`:

```js

constructor(super) {
  super();
  this.state = {
    currentDate: Date.now()
  };
}
```

2018-03-02 13:25 UTC, okonet commented on components/Countdown.js
> +    setInterval(this.updateCountdown, 1000);
You forgot to clean up the interval in the `componentWillUnmount`. This will cause a memory leak...

2018-03-02 13:25 UTC, okonet commented on components/Countdown.js
> +    this.updateState();
So, here, instead of all this you could just `this.setState({ currentDate: Date.now() })`. This would trigger re-render.

2018-03-02 13:25 UTC, okonet commented on components/Countdown.js
> +  updateState() {
The whole method is then not needed.

2018-03-02 13:25 UTC, okonet commented on components/Countdown.js
> +  getDifferenceInDates() {
This one, too, can be removed.

2018-03-02 13:25 UTC, okonet commented on components/Countdown.js
> +  initialDate: PropTypes.string,
I'd call the `initialDate` as `toDate` since it's the countdown and it counts _to_ some specific date.

2018-03-02 13:26 UTC, okonet commented
I can help you with CSS after you resolve the comments.

2018-03-02 13:48 UTC, Scoombe commented
@okonet  I have made the changes you have requested. Thanks, for pointing me in the right direction, I was having problems with the concept of when react was calling the reload.

2018-03-05 19:03 UTC, merged

2018-03-05 19:04 UTC, bebraw commented
Merged! Thanks a lot for your contribution @Scoombe. Are you coming to the conference?

2018-03-05 20:29 UTC, okonet commented
Nice work!